// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 常量表 GameConst。访问：GameConst.Instance
    /// </summary>
    [Serializable]
    public sealed class GameConst : ConfigConstBase<GameConst>
    {
        /// <summary>
        /// 帧数
        /// </summary>
        public int GameFps;

        /// <summary>
        /// 默认英雄ID
        /// </summary>
        public int DefaultHeroId;

        /// <summary>
        /// 多少筹码换1积分
        /// </summary>
        public int ChipsForPoints;

        /// <summary>
        /// 多少积分换1金币
        /// </summary>
        public int ExchangePointsForGoldCoins;

        /// <summary>
        /// 每关第1回合基础下注金额
        /// </summary>
        public int BasicBettingAmount;

        /// <summary>
        /// 后续每回合下注金额
        /// </summary>
        public int AfterBettingAmount;

        /// <summary>
        /// 商店首次刷新费用
        /// </summary>
        public int ShopRefreshFirst;

        /// <summary>
        /// 商店后续刷新费用增长
        /// </summary>
        public int ShopRefreshAfter;

        /// <summary>
        /// 商店刷新费用增长次数上限
        /// </summary>
        public int ShopRefreshGoldUpNumMax;

        /// <summary>
        /// 金币道具icon
        /// </summary>
        public string GoldIcon;

        /// <summary>
        /// 第一次抽取天赋所需金币
        /// </summary>
        public int TalentChestNeedGold;

        /// <summary>
        /// 每局初始金币数
        /// </summary>
        public int PlayerInitialGoldNum;

        /// <summary>
        /// 局内伤害与金币的转换比例
        /// </summary>
        public int[] DamageTurnToGold;

        /// <summary>
        /// 每击杀一名敌人给予结算金币加成
        /// </summary>
        public int KillMonsterGetGold;

        /// <summary>
        /// 每通过1关后,英雄回复最大生命值的百分比(0为不生效)
        /// </summary>
        public int HeroReplyHpPerLevelClear;

        /// <summary>
        /// 体力上限(每日回满到此值)
        /// </summary>
        public int EnergyMax;

        /// <summary>
        /// 每局消耗体力
        /// </summary>
        public int EnergyCostPerRun;

        /// <summary>
        /// 每日体力重置时刻(凌晨X点跨日)
        /// </summary>
        public int EnergyDailyResetHour;

        /// <summary>
        /// 每日看广告补充体力次数
        /// </summary>
        public int EnergyAdRefillDailyLimit;

        /// <summary>
        /// 天赋页面规则描述
        /// </summary>
        public string[] TalentDesc;

        /// <summary>
        /// 初始默认可携带圣物最大数量
        /// </summary>
        public int DefaultRelicNumMax;

        /// <summary>
        /// 广告商店每次购买获得体力
        /// </summary>
        public int AdShopStaminaPerBuy;

        /// <summary>
        /// 广告商店每日可购买体力次数
        /// </summary>
        public int AdShopStaminaDailyLimit;

        /// <summary>
        /// 广告商店每次购买获得金币
        /// </summary>
        public int AdShopGoldPerBuy;

        /// <summary>
        /// 广告商店每日可购买金币次数
        /// </summary>
        public int AdShopGoldDailyLimit;

        /// <summary>
        /// 普通品质圣物框颜色
        /// </summary>
        public string OrdinaryRelicColor;

        /// <summary>
        /// 稀有品质圣物框颜色
        /// </summary>
        public string RareRelicColor;

        /// <summary>
        /// 史诗品质圣物框颜色
        /// </summary>
        public string EpicRelicColor;

        /// <summary>
        /// 传说品质圣物框颜色
        /// </summary>
        public string LegendRelicColor;

        /// <summary>
        /// 每关默认搓牌使用次数
        /// </summary>
        public int DefaultSkillShuffleNum;

        /// <summary>
        /// 每关默认换牌使用次数
        /// </summary>
        public int DefaultSkillReplaceNum;

        /// <summary>
        /// 每关默认看牌使用次数
        /// </summary>
        public int DefaultSkillPerspectiveNum;

        /// <summary>
        /// 每次抽取天赋金币累加
        /// </summary>
        public int TalentNeedChestGold;

        /// <summary>
        /// 每有1个未使用的技能,结算时提供20金币
        /// </summary>
        public int EverySkillProvideGold;

        /// <summary>
        /// PVP排队多少秒未满4人时用机器人补满(0=立即补满)
        /// </summary>
        public int PvpBotFillDelaySeconds;

    }
}

