// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 HeroEffectsConfig。访问：HeroEffectsConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class HeroEffectsConfig : ConfigRowBase<HeroEffectsConfig>
    {
        /// <summary>
        /// 特效类型
        /// </summary>
        public EffectsType Type;

        /// <summary>
        /// 资源名字
        /// </summary>
        public string Effects;

        /// <summary>
        /// 效果时长
        /// </summary>
        public float Time;

    }
}

