// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 MonsterConfig。访问：MonsterConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class MonsterConfig : ConfigRowBase<MonsterConfig>
    {
        /// <summary>
        /// 怪物Id
        /// </summary>
        public int MonsterId;

        /// <summary>
        /// 等级
        /// </summary>
        public int MonsterLevel;

        /// <summary>
        /// 生命值
        /// </summary>
        public int MonsterHp;

        /// <summary>
        /// 攻击力
        /// </summary>
        public int MonsterDamage;

        /// <summary>
        /// 怪物类型
        /// </summary>
        public MonsterType Type;

        /// <summary>
        /// 怪物名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 怪物介绍
        /// </summary>
        public string Desc;

        /// <summary>
        /// 怪物icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 怪物底图
        /// </summary>
        public string BaseMap;

        /// <summary>
        /// 怪物血条
        /// </summary>
        public string HealthBar;

        /// <summary>
        /// 怪物机制
        /// </summary>
        public int MonsterEntry;

    }
}

