// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 MonsterLogicConfig。访问：MonsterLogicConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class MonsterLogicConfig : ConfigRowBase<MonsterLogicConfig>
    {
        /// <summary>
        /// 手牌类型
        /// </summary>
        public HandType Type1;

        /// <summary>
        /// 最大点数类型
        /// </summary>
        public PointType Type2;

        /// <summary>
        /// 弃牌概率
        /// </summary>
        public int FoldPro;

        /// <summary>
        /// 跟注概率
        /// </summary>
        public int FollowPro;

        /// <summary>
        /// 加注概率
        /// </summary>
        public int RaisePro;

        /// <summary>
        /// 下注后弃牌概率
        /// </summary>
        public int PlaceFoldPro;

        /// <summary>
        /// 超额下注后弃牌概率
        /// </summary>
        public int ExcessPlacePro;

    }
}

