// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 PvpBotConfig。访问：PvpBotConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class PvpBotConfig : ConfigRowBase<PvpBotConfig>
    {
        /// <summary>
        /// 昵称
        /// </summary>
        public string NickName;

        /// <summary>
        /// 头像URL
        /// </summary>
        public string AvatarUrl;

        /// <summary>
        /// 英雄Id(0=默认)
        /// </summary>
        public int HeroId;

        /// <summary>
        /// 是否启用
        /// </summary>
        public bool Enabled;

    }
}

