// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 PvpModeConfig。访问：PvpModeConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class PvpModeConfig : ConfigRowBase<PvpModeConfig>
    {
        /// <summary>
        /// 展示名
        /// </summary>
        public string Name;

        /// <summary>
        /// 开房人数
        /// </summary>
        public int PlayerCount;

        /// <summary>
        /// 开局金币
        /// </summary>
        public int InitialGold;

        /// <summary>
        /// 商店秒数
        /// </summary>
        public int ShopSeconds;

        /// <summary>
        /// 剩2人跳过野怪轮
        /// </summary>
        public bool SkipMonsterWhenTwoLeft;

        /// <summary>
        /// 第1到4名奖励
        /// </summary>
        public int[] RankReward;

        /// <summary>
        /// 每轮伤害加成
        /// </summary>
        public float DamageRoundScale;

        /// <summary>
        /// 选牌秒数
        /// </summary>
        public int OpenPhaseSeconds;

    }
}

