// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 PvpRoundConfig。访问：PvpRoundConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class PvpRoundConfig : ConfigRowBase<PvpRoundConfig>
    {
        /// <summary>
        /// 所属模式
        /// </summary>
        public int ModeId;

        /// <summary>
        /// 全局轮次
        /// </summary>
        public int Round;

        /// <summary>
        /// 本轮对手
        /// </summary>
        public PvpFightKind FightKind;

        /// <summary>
        /// 野怪组Id
        /// </summary>
        public int MonsterGroup;

        /// <summary>
        /// 本轮基础金币
        /// </summary>
        public int GoldBase;

    }
}

