// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 TalentConfig。访问：TalentConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class TalentConfig : ConfigRowBase<TalentConfig>
    {
        /// <summary>
        /// 天赋Id
        /// </summary>
        public int TalentId;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 品质
        /// </summary>
        public QualityType Type;

        /// <summary>
        /// 概率
        /// </summary>
        public float ChestProbability;

        /// <summary>
        /// icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 天赋等级
        /// </summary>
        public int TalentLevel;

        /// <summary>
        /// 天赋机制
        /// </summary>
        public int TalentEntry;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

