using System.Text;

namespace ConfigExporter;

/// <summary>
/// 根据配置表结构生成 Unity C#（DTO / ConfigTables / 资源路径 partial）。
/// </summary>
public static class CsharpGenerator
{
    private const string AutoHeader = """
        // <auto-generated>
        // 本文件由 ConfigExporter 自动生成，请勿手动修改。
        // </auto-generated>
        """;

    public static void Generate(IReadOnlyList<ConfigTable> tables, string outputDir)
    {
        if (tables.Count == 0)
            throw new InvalidOperationException("没有可生成的配置表。");

        Directory.CreateDirectory(outputDir);

        // 清理旧的生成表文件，但保留目录；固定文件名会覆盖
        foreach (var old in Directory.GetFiles(outputDir, "*.cs"))
        {
            var name = Path.GetFileName(old);
            if (name is "ConfigTables.cs" or "ResResourcePaths.Config.g.cs")
                continue;
            // 只删看起来是表 DTO 的：与当前导出集无关的也删，避免删表后残留
            File.Delete(old);
        }

        foreach (var table in tables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
        {
            var path = Path.Combine(outputDir, $"{table.Name}.cs");
            File.WriteAllText(path, GenerateTableClass(table), new UTF8Encoding(false));
            Console.WriteLine($"[CSV→C#][{table.Kind}] {table.Name}.cs → {path}");
        }

        var tablesPath = Path.Combine(outputDir, "ConfigTables.cs");
        File.WriteAllText(tablesPath, GenerateConfigTables(tables), new UTF8Encoding(false));
        Console.WriteLine($"[CSV→C#] ConfigTables.cs → {tablesPath}");

        var pathsFile = Path.Combine(outputDir, "ResResourcePaths.Config.g.cs");
        File.WriteAllText(pathsFile, GenerateResourcePaths(tables), new UTF8Encoding(false));
        Console.WriteLine($"[CSV→C#] ResResourcePaths.Config.g.cs → {pathsFile}");
    }

    private static string GenerateTableClass(ConfigTable table)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace App.Config");
        sb.AppendLine("{");

        if (table.Kind == ConfigTableKind.Const)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 常量表 {table.Name}。访问：{table.Name}.Instance");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {table.Name} : ConfigConstBase<{table.Name}>");
            sb.AppendLine("    {");
            AppendFields(sb, table, skipId: false);
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 配置表 {table.Name}。访问：{table.Name}.Get(id) / TryGet / All");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {table.Name} : ConfigRowBase<{table.Name}>");
            sb.AppendLine("    {");
            AppendFields(sb, table, skipId: true);
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private static void AppendFields(StringBuilder sb, ConfigTable table, bool skipId)
    {
        for (var i = 0; i < table.FieldNames.Count; i++)
        {
            var name = table.FieldNames[i];
            if (skipId && string.Equals(name, "Id", StringComparison.Ordinal))
                continue;

            ValidateIdentifier(name, table.Name);

            var excelType = i < table.FieldTypes.Count ? table.FieldTypes[i] : "string";
            var csharpType = MapType(excelType, table.Name, name);
            var comment = i < table.FieldComments.Count ? table.FieldComments[i] : string.Empty;

            if (!string.IsNullOrWhiteSpace(comment))
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {EscapeXml(comment.Trim())}");
                sb.AppendLine("        /// </summary>");
            }

            sb.AppendLine($"        public {csharpType} {name};");
            sb.AppendLine();
        }
    }

    private static string GenerateConfigTables(IReadOnlyList<ConfigTable> tables)
    {
        var ordered = tables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase).ToList();
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using App.Resources;");
        sb.AppendLine("using Framework.Assets;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace App.Config");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 启动时加载全部配置表。业务访问走各表自身静态接口。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class ConfigTables");
        sb.AppendLine("    {");
        sb.AppendLine("        public static async Task LoadAsync(IResourceService resources)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (resources == null)");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new ArgumentNullException(nameof(resources));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var table in ordered)
        {
            var varName = ToLocalName(table.Name) + "Asset";
            sb.AppendLine(
                $"            var {varName} = await resources.LoadAsync<TextAsset>(ResResourcePaths.{table.Name});");
        }

        sb.AppendLine();

        foreach (var table in ordered)
        {
            var varName = ToLocalName(table.Name) + "Asset";
            if (table.Kind == ConfigTableKind.Const)
            {
                sb.AppendLine(
                    $"            {table.Name}.Load(ConfigJson.FromObjectJson<{table.Name}>({varName}.text));");
            }
            else
            {
                sb.AppendLine(
                    $"            {table.Name}.Load(ConfigJson.FromArrayJson<{table.Name}>({varName}.text));");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string GenerateResourcePaths(IReadOnlyList<ConfigTable> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("namespace App.Resources");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ResResourcePaths");
        sb.AppendLine("    {");
        foreach (var table in tables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"        public const string {table.Name} = \"Config/{table.Name}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    public static string MapType(string excelType, string tableName, string fieldName)
    {
        var t = (excelType ?? "string").Trim().ToLowerInvariant();
        return t switch
        {
            "int" or "int32" => "int",
            "long" or "int64" => "long",
            "float" or "single" => "float",
            "double" or "number" => "double",
            "bool" or "boolean" => "bool",
            "string" or "" => "string",
            "int[]" or "int32[]" => "int[]",
            "long[]" or "int64[]" => "long[]",
            "float[]" or "single[]" => "float[]",
            "double[]" or "number[]" => "double[]",
            "bool[]" or "boolean[]" => "bool[]",
            "string[]" => "string[]",
            _ => throw new FormatException($"[{tableName}.{fieldName}] 不支持的类型: {excelType}")
        };
    }

    private static void ValidateIdentifier(string name, string tableName)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new FormatException($"[{tableName}] 字段名为空");
        if (!(char.IsLetter(name[0]) || name[0] == '_'))
            throw new FormatException($"[{tableName}.{name}] 字段名不是合法 C# 标识符");
        for (var i = 1; i < name.Length; i++)
        {
            if (!(char.IsLetterOrDigit(name[i]) || name[i] == '_'))
                throw new FormatException($"[{tableName}.{name}] 字段名不是合法 C# 标识符");
        }
    }

    private static string ToLocalName(string typeName)
    {
        if (string.IsNullOrEmpty(typeName))
            return "table";
        return char.ToLowerInvariant(typeName[0]) + typeName[1..];
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
