using System.Text;

namespace ConfigExporter;

/// <summary>
/// 根据配置表结构生成 Unity C#（DTO / ConfigTables / 资源路径 partial）。
/// </summary>
public static class CsharpGenerator
{
    private const string AutoHeader = """
        // <auto-generated>
        // 本文件由 ConfigExporter 自动生成，请勿手动修改。
        // </auto-generated>
        """;

    public static void Generate(
        IReadOnlyList<ConfigTable> tables,
        IReadOnlyList<EnumDefinition> enums,
        string outputDir)
    {
        if (tables.Count == 0)
            throw new InvalidOperationException("没有可生成的配置表。");

        var runtimeTables = tables
            .Where(table => table.Kind != ConfigTableKind.Enum)
            .ToList();

        Directory.CreateDirectory(outputDir);

        // 生成目录全部归工具管理，删表后不保留旧代码。
        foreach (var old in Directory.GetFiles(outputDir, "*.cs"))
            File.Delete(old);

        // 配表行类与枚举只生成到共享层（Card/Assets/Shared/Contracts/Config），客户端直接用。
        // 这里只生成客户端加载层：ConfigTables（读 JSON 灌进各表静态注册表）+ 资源路径。
        var tablesPath = Path.Combine(outputDir, "ConfigTables.cs");
        File.WriteAllText(tablesPath, GenerateConfigTables(runtimeTables), new UTF8Encoding(false));
        Console.WriteLine($"[CSV→C#] ConfigTables.cs → {tablesPath}");

        var pathsFile = Path.Combine(outputDir, "ResResourcePaths.Config.g.cs");
        File.WriteAllText(pathsFile, GenerateResourcePaths(runtimeTables), new UTF8Encoding(false));
        Console.WriteLine($"[CSV→C#] ResResourcePaths.Config.g.cs → {pathsFile}");
    }

    private static void AppendFields(
        StringBuilder sb,
        ConfigTable table,
        IReadOnlyDictionary<string, string> enumNames,
        bool skipId)
    {
        for (var i = 0; i < table.FieldNames.Count; i++)
        {
            var name = table.FieldNames[i];
            if (skipId && string.Equals(name, "Id", StringComparison.Ordinal))
                continue;

            ValidateIdentifier(name, table.Name);

            var excelType = i < table.FieldTypes.Count ? table.FieldTypes[i] : "string";
            var csharpType = MapType(excelType, table.Name, name, enumNames);
            var comment = i < table.FieldComments.Count ? table.FieldComments[i] : string.Empty;

            if (!string.IsNullOrWhiteSpace(comment))
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {EscapeXml(comment.Trim())}");
                sb.AppendLine("        /// </summary>");
            }

            sb.AppendLine($"        public {csharpType} {name};");
            sb.AppendLine();
        }
    }

    private static string GenerateConfigTables(IReadOnlyList<ConfigTable> tables)
    {
        var ordered = tables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase).ToList();
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using App.Resources;");
        sb.AppendLine("using CardShare.Contracts.Config;");
        sb.AppendLine("using Framework.Assets;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace App.Config");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 启动时加载全部配置表（共享类），业务访问走各表自身静态接口。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class ConfigTables");
        sb.AppendLine("    {");
        sb.AppendLine("        public static async Task LoadAsync(IResourceService resources)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (resources == null)");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new ArgumentNullException(nameof(resources));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var table in ordered)
        {
            var varName = ToLocalName(table.Name) + "Asset";
            sb.AppendLine(
                $"            var {varName} = await resources.LoadAsync<TextAsset>(ResResourcePaths.{table.Name});");
        }

        sb.AppendLine();

        foreach (var table in ordered)
        {
            var varName = ToLocalName(table.Name) + "Asset";
            if (table.Kind == ConfigTableKind.Const)
            {
                sb.AppendLine(
                    $"            {table.Name}.Load(ConfigJson.FromObjectJson<{table.Name}>({varName}.text));");
            }
            else
            {
                sb.AppendLine(
                    $"            {table.Name}.Load(ConfigJson.FromArrayJson<{table.Name}>({varName}.text));");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string GenerateResourcePaths(IReadOnlyList<ConfigTable> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("namespace App.Resources");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ResResourcePaths");
        sb.AppendLine("    {");
        foreach (var table in tables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"        public const string {table.Name} = \"Config/{table.Name}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    private static string GenerateEnums(IReadOnlyList<EnumDefinition> enums, string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        foreach (var definition in enums.OrderBy(item => item.Name, StringComparer.OrdinalIgnoreCase))
        {
            ValidateIdentifier(definition.Name, "EnumConfig");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 由 EnumConfig.xlsx 生成的 {definition.Name} 枚举。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public enum {definition.Name}");
            sb.AppendLine("    {");

            var memberNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var member in definition.Members)
            {
                ValidateIdentifier(member.Name, definition.Name);
                if (!memberNames.Add(member.Name))
                    throw new FormatException($"枚举 {definition.Name} 成员重复: {member.Name}");

                if (!string.IsNullOrWhiteSpace(member.Description))
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {EscapeXml(member.Description)}");
                    sb.AppendLine("        /// </summary>");
                }

                sb.AppendLine($"        {member.Name} = {member.Value},");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    public static void GenerateShared(
        IReadOnlyList<ConfigTable> tables,
        IReadOnlyList<EnumDefinition> enums,
        string outputDir)
    {
        if (tables.Count == 0)
            throw new InvalidOperationException("没有可生成的配置表。");

        var runtimeTables = tables
            .Where(table => table.Kind != ConfigTableKind.Enum)
            .ToList();
        var enumNames = enums.ToDictionary(
            definition => definition.Name,
            definition => definition.Name,
            StringComparer.OrdinalIgnoreCase);

        Directory.CreateDirectory(outputDir);
        foreach (var old in Directory.GetFiles(outputDir, "*.cs"))
            File.Delete(old);

        foreach (var table in runtimeTables.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
        {
            var path = Path.Combine(outputDir, $"{table.Name}.cs");
            File.WriteAllText(path, GenerateSharedTableClass(table, enumNames), new UTF8Encoding(false));
            Console.WriteLine($"[CSV→Contracts][{table.Kind}] {table.Name}.cs → {path}");
        }

        if (enums.Count > 0)
        {
            var enumPath = Path.Combine(outputDir, "Enums.g.cs");
            File.WriteAllText(enumPath, GenerateEnums(enums, "CardShare.Contracts.Config"), new UTF8Encoding(false));
            Console.WriteLine($"[CSV→Contracts][Enum] Enums.g.cs → {enumPath}");
        }
    }

    private static string GenerateSharedTableClass(
        ConfigTable table,
        IReadOnlyDictionary<string, string> enumNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoHeader);
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace CardShare.Contracts.Config");
        sb.AppendLine("{");
        if (table.Kind == ConfigTableKind.Const)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 常量表 {table.Name}。访问：{table.Name}.Instance");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {table.Name} : ConfigConstBase<{table.Name}>");
            sb.AppendLine("    {");
            AppendFields(sb, table, enumNames, skipId: false);
        }
        else
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// 配置表 {table.Name}。访问：{table.Name}.Get(id) / TryGet / All");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {table.Name} : ConfigRowBase<{table.Name}>");
            sb.AppendLine("    {");
            AppendFields(sb, table, enumNames, skipId: true);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    public static string MapType(
        string excelType,
        string tableName,
        string fieldName,
        IReadOnlyDictionary<string, string> enumNames)
    {
        var original = (excelType ?? "string").Trim();
        var isArray = original.EndsWith("[]", StringComparison.Ordinal);
        var elementType = isArray ? original[..^2].Trim() : original;
        var normalized = elementType.ToLowerInvariant();

        var primitive = normalized switch
        {
            "int" or "int32" => "int",
            "long" or "int64" => "long",
            "float" or "single" => "float",
            "double" or "number" => "double",
            "bool" or "boolean" => "bool",
            "string" or "" => "string",
            _ => null
        };

        if (primitive is not null)
            return primitive + (isArray ? "[]" : string.Empty);

        if (enumNames.TryGetValue(elementType, out var enumName))
            return enumName + (isArray ? "[]" : string.Empty);

        throw new FormatException(
            $"[{tableName}.{fieldName}] 不支持的类型: {excelType}，自定义枚举需在 EnumConfig.xlsx 中定义");
    }

    private static void ValidateIdentifier(string name, string tableName)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new FormatException($"[{tableName}] 字段名为空");
        if (!(char.IsLetter(name[0]) || name[0] == '_'))
            throw new FormatException($"[{tableName}.{name}] 字段名不是合法 C# 标识符");
        for (var i = 1; i < name.Length; i++)
        {
            if (!(char.IsLetterOrDigit(name[i]) || name[i] == '_'))
                throw new FormatException($"[{tableName}.{name}] 字段名不是合法 C# 标识符");
        }
    }

    private static string ToLocalName(string typeName)
    {
        if (string.IsNullOrEmpty(typeName))
            return "table";
        return char.ToLowerInvariant(typeName[0]) + typeName[1..];
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
