// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class CollectionConfig
    {
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 收藏品icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 品质类型
        /// </summary>
        public QualityType Type;

        /// <summary>
        /// 解锁条件
        /// </summary>
        public int UnlockCondition;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

