// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class DialogueGroupConfig
    {
        public int Id;

        /// <summary>
        /// 怪物Id(1001~1005普通,2001Boss,3001精英)
        /// </summary>
        public int MonsterId;

        /// <summary>
        /// 玩家台词(回应怪物,&lt;=20字)
        /// </summary>
        public string PlayerTalk;

        /// <summary>
        /// 怪物台词(怪物先说,&lt;=20字)
        /// </summary>
        public string MonsterTalk;

    }
}

