// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class GuideStepConfig
    {
        public int Id;

        /// <summary>
        /// 所属组
        /// </summary>
        public int GroupId;

        /// <summary>
        /// 顺序
        /// </summary>
        public int Order;

        /// <summary>
        /// 步骤类型
        /// </summary>
        public GuideStepType StepType;

        /// <summary>
        /// 高亮目标
        /// </summary>
        public string TargetId;

        /// <summary>
        /// 气泡文案
        /// </summary>
        public string Text;

        /// <summary>
        /// 等待处理器
        /// </summary>
        public string WaitHandler;

        /// <summary>
        /// 等待参数
        /// </summary>
        public string WaitParam;

        /// <summary>
        /// 显示蒙版
        /// </summary>
        public bool ShowMask;

        /// <summary>
        /// 显示手指
        /// </summary>
        public bool ShowFinger;

        /// <summary>
        /// 高亮内边距
        /// </summary>
        public int Padding;

    }
}

