// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 GuideGroupConfig。访问：GuideGroupConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class GuideGroupConfig
    {
        public int Id;

        /// <summary>
        /// 组名
        /// </summary>
        public string Name;

        /// <summary>
        /// 触发类型
        /// </summary>
        public GuideTriggerType TriggerType;

        /// <summary>
        /// 触发参数
        /// </summary>
        public string TriggerParam;

        /// <summary>
        /// 可否跳过
        /// </summary>
        public bool Skipable;

        /// <summary>
        /// 是否启用
        /// </summary>
        public bool Enabled;

    }
}

