// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class HandScoreConfig
    {
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 牌型顺位
        /// </summary>
        public int Level;

        /// <summary>
        /// 牌型
        /// </summary>
        public HandType Type;

        /// <summary>
        /// 基础倍率
        /// </summary>
        public float BasicMagnification;

    }
}

