// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class HeroEntryConfig
    {
        public int Id;

        /// <summary>
        /// 效果名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 机制类型
        /// </summary>
        public MechanismType Type;

        /// <summary>
        /// 值
        /// </summary>
        public float Value;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

