// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 HeroConfig。访问：HeroConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class HeroConfig
    {
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 生命值
        /// </summary>
        public int Hp;

        /// <summary>
        /// 攻击力
        /// </summary>
        public int HeroDamage;

        /// <summary>
        /// 暴击率
        /// </summary>
        public float Critical;

        /// <summary>
        /// 暴击伤害
        /// </summary>
        public float CriticalDamage;

        /// <summary>
        /// 形象icon
        /// </summary>
        public string Icon;

        /// <summary>
        /// 英雄机制id
        /// </summary>
        public int[] HeroEntryId;

        /// <summary>
        /// 解锁难度条件
        /// </summary>
        public int UnlockCondition;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

