// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class ItemConfig
    {
        public int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public string Name;

        /// <summary>
        /// 技能图标
        /// </summary>
        public string Icon;

        /// <summary>
        /// 每回合可使用次数
        /// </summary>
        public int NumOfUsesPerRound;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

