// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    /// <summary>
    /// 配置表 LevelConfig。访问：LevelConfig.Get(id) / TryGet / All
    /// </summary>
    [Serializable]
    public sealed class LevelConfig
    {
        public int Id;

        /// <summary>
        /// 难度
        /// </summary>
        public int Difficulty;

        /// <summary>
        /// 关卡
        /// </summary>
        public int Level;

        /// <summary>
        /// 机制数量
        /// </summary>
        public int LevelEntryNum;

        /// <summary>
        /// 怪物组id
        /// </summary>
        public int[] MonsterGroup;

        /// <summary>
        /// 通关金币
        /// </summary>
        public int GetGold;

        /// <summary>
        /// 敌人最大牌型顺位限制
        /// </summary>
        public int MonsterCardHandScoreLevelLimit;

    }
}

