// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class MonsterGroupConfig
    {
        public int Id;

        /// <summary>
        /// 怪物Id
        /// </summary>
        public int MonsterId;

        /// <summary>
        /// 怪物等级
        /// </summary>
        public int MonsterLevel;

    }
}

