// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class PvpRoundConfig
    {
        public int Id;

        /// <summary>
        /// 所属模式
        /// </summary>
        public int ModeId;

        /// <summary>
        /// 全局轮次
        /// </summary>
        public int Round;

        /// <summary>
        /// 本轮对手
        /// </summary>
        public PvpFightKind FightKind;

        /// <summary>
        /// 野怪组Id
        /// </summary>
        public int MonsterGroup;

        /// <summary>
        /// 本轮基础金币
        /// </summary>
        public int GoldBase;

    }
}

