// <auto-generated>
// 本文件由 ConfigExporter 自动生成，请勿手动修改。
// </auto-generated>
using System;

namespace CardShare.Contracts.Config
{
    [Serializable]
    public sealed class UnlockConditionConfig
    {
        public int Id;

        /// <summary>
        /// 条件类型
        /// </summary>
        public ContidionType Type;

        /// <summary>
        /// 每次叠加值
        /// </summary>
        public int StackedValue;

        /// <summary>
        /// 达成值
        /// </summary>
        public int Value;

        /// <summary>
        /// 描述
        /// </summary>
        public string Desc;

    }
}

