<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Card.Contracts\Card.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Card.Battle\Card.Battle.csproj" />
    <ProjectReference Include="..\..\src\Card.Domain\Card.Domain.csproj" />
    <ProjectReference Include="..\..\src\Card.Infrastructure\Card.Infrastructure.csproj" />
  </ItemGroup>

</Project>
